### ISSUE TITLE
Edge browser interface and tab title font didn't change.

### ISSUE THREAD

**Issue by HumanMus1c** [Tatsu-syo/noMeiryoUI#103]
After font set up, the Explorer's font has changed. But Edge browser interface and tab title's font didn't.
![image](https://github.com/Tatsu-syo/noMeiryoUI/assets/46023154/3b07ff46-cfb5-4493-9ef3-564ecc264421)
![image](https://github.com/Tatsu-syo/noMeiryoUI/assets/46023154/cffd2066-e210-4a40-8f8e-bdd0c3efb923)

**Comment by Tatsu-syo** [comment]
Edge browser ignore system font, and changees user interface unpredictably.
I cannot do anything myself.
Use feedback hub.
