### ISSUE TITLE
Discussions issue towards next to 3.3.0

### ISSUE THREAD

**Issue by Tatsu-syo** [Tatsu-syo/noMeiryoUI#107]
I release No!! Meiryo UI!! Version 3.3.0 on Feb,25 2024 PM (JST).

In version 3.3.0 there are some problem rests.

- Missing translations.

This issue is discussion space for next release.

Management way is same as version 3.3.0. When pull request is coming, write information in this issue, and discussion about pull request in pull request.

I planning next release, when new translation is coming.

**Comment by Tatsu-syo** [comment]
@abc0922001 sends translation for zh-TW on [Update zh-TW.lng](https://github.com/Tatsu-syo/noMeiryoUI/pull/108) .
Please check it and if no problems found, I'll merge it next Thursday.

**Comment by Tatsu-syo** [comment]
@kingofotaku sends translations for zh-cn on [Updated Simplified Chinese help file translation and example screenshots to the latest version.](https://github.com/Tatsu-syo/noMeiryoUI/pull/110) .
Please check it and if no problems found, I'll merge it next Friday.

And @kingofotaku tells me small glitch [フォント設定が初期設定でないと、NoMeiryoUIのタイトルが消えます。](https://github.com/Tatsu-syo/noMeiryoUI/issues/111) .
If discussion continues, I release next version with fix glitch and include translations snapshot.

**Comment by Tatsu-syo** [comment]
I reproduce glitch and fix it.
But it's weird.

I compile on Visual Studio 2008, this issue occurred.
But I compiled it on Visual Studio 2022 and it's compiler, this issue not occurred.
But Microsoft anti virus products judges it's virus.
I use Visual Studio 2012 and it's compiler this issue not occurred and Microsoft anti virus products don't judge it's virus.

How about it?

For such and such reasons, I fix bug and release new version and close issue.

**Comment by Tatsu-syo** [comment]
This is why, I release version 3.3.1 and this issue cloaed.

**Comment by kingofotaku** [comment]
> This is why, I release version 3.3.1 and this issue cloaed.

3.31 doesn't seem to merge the translation update I submitted (zh-CN.lng)

**Comment by Tatsu-syo** [comment]
@kingofotaku  Sorry, I mistake when archive created.
I made new release archive.
Please check it.

**Comment by kingofotaku** [comment]
> @kingofotaku Sorry, I mistake when archive created. I made new release archive. Please check it.

I checked. Thanks for the correction.

**Comment by Tatsu-syo** [comment]
@kingofotaku Thanks for check.

I really release No!! Meiryo UI. And this issue mark closed.
