### ISSUE TITLE
フォント設定が初期設定でないと、NoMeiryoUIのタイトルが消えます。

### ISSUE THREAD

**Issue by kingofotaku** [Tatsu-syo/noMeiryoUI#111]
初期設定だと↓
![image](https://github.com/Tatsu-syo/noMeiryoUI/assets/12953574/259bf7f0-0ecc-4fa9-ab6b-f103689a575a)
しかし一箇所でも変えるとこんなふうになります（どのフォントにしても同じく）↓
![image](https://github.com/Tatsu-syo/noMeiryoUI/assets/12953574/92462aad-56d1-425a-800a-61a2809da29f)

**Comment by Tatsu-syo** [comment]
Probably, I missed title bar height calculation.
To set font settings and window element size settings use same API and structure.
I forget title bar height calculation and title bar height changed insufficient height to draw application title.
I fix it next version.
Thanks and sorry.

**Comment by Tatsu-syo** [comment]
I reproduce glitch and fix it.
But it's weird.

I compile on Visual Studio 2008, this issue occurred.
But I compiled it on Visual Studio 2022 and it's compiler, this issue not occurred.
But Microsoft anti virus products judges it's virus.
I use Visual Studio 2012 and it's compiler this issue not occurred and Microsoft anti virus products don't judge it's virus.

How about it?

For such and such reasons, I fix bug and release new version and close issue.
