### ISSUE TITLE
Win 11 Webpage font rendering error in all browsers after modifying fonts, can't be recovered

### ISSUE THREAD

**Issue by Yikai-Liao** [Tatsu-syo/noMeiryoUI#114]
After modifying fonts using 3.3.1, I've encountered strange font rendering errors when opening many web pages, and modifying back to the default Yahei UI fonts can't fix the problem.
Since there is no backup before using it, it is difficult for me to restore it at the moment. So I'm asking for help here.

edge, firefox loads the page with the same rendering error.

![image](https://github.com/Tatsu-syo/noMeiryoUI/assets/110762732/189fe102-b686-4fb7-806d-a18ec9caf196)

Feishu(lark) also get the same error.
![image](https://github.com/Tatsu-syo/noMeiryoUI/assets/110762732/bf4b2e72-6bae-4467-a29e-63063a085044)

File Explorer, word and other software like wechat work normally.

**Comment by lanzhiquan** [comment]
库主是个日本人，你在这发毛中文。

**Comment by Yikai-Liao** [comment]
> 库主是个日本人，你在这发毛中文。

Sorry, I saw a bunch of Chinese issues so I wrote Chinese.

**Comment by Yikai-Liao** [comment]
update: following the faq, I create a temporary account. Browser still not working properly with new account.

**Comment by Tatsu-syo** [comment]
In screen shot, it looks like font cache is broken.
The reason is some software look normally, and some software and some charactors look broken.
Please try to clear font cache.

**Comment by Yikai-Liao** [comment]
Thanks for the advice, but since I was in a hurry, I just reinstalled the system.
