### ISSUE TITLE
Can't use default path for command

### ISSUE THREAD

**Issue by doumeki** [Tatsu-syo/noMeiryoUI#12]
Hi, I use latest version (2.36), old version not tested.
cannot use  noMeiryoUI.exe "conf.ini" -set , must use  noMeiryoUI ".\noMeiryoUI" -set

**Comment by Tatsu-syo** [comment]
@doumeki 
When I read configuration file, I use Windows API GetPrivateProfileString.
This is why when you specify current directory, noMeiryoUI can't read setting file on current directory.
On work around, please add path.
I'll fix next version of noMeiryoUI.

**Comment by Tatsu-syo** [comment]
@doumeki
Today, I released No!! Meiryo UI Version 2.40.
Version 2.40 fixed bug.
Please try this version.

**Comment by doumeki** [comment]
thanks very much. 
You are very kindly
