### ISSUE TITLE
Next Version 2.40 help translation

### ISSUE THREAD

**Issue by Tatsu-syo** [Tatsu-syo/noMeiryoUI#13]
@devBug 
@kingofotaku
@austin-chang 

現在、Version 2.40リリースに向けて準備を進めております。
変更点は、

- 適用ボタンを追加しました。
- ウインドウの項目を全体設定と個別設定でグループ化しました。
- カレントディレクトリの設定ファイルを読み込めない不具合を修正しました。

となります。現在日本語と英語のヘルプの訳がある状態なので、こちらを参照の上訳をお願いします。
よろしくお願いいたします。

I prepare to next release version 2.40.
Changes is below.

- Add apply button.
- Controls are grouped.
- Fixed bug cannot use default path when you specified setting file.

Please translate release note. For reference English and Japanese language is ready.
If translation don't arrive at May 31, I will release noMeiryo UI!! without translation partially.
Best regards.

**Comment by kingofotaku** [comment]
メール見てきました。それでお手数おかけしますが、ビルダ済みのプログラムをこちらに送っていただけないでしょうか？（ヘルプファイルを翻訳するのに必要です）わたしのメアドはこちら：lzsqq754318010@gmail.com

**Comment by Tatsu-syo** [comment]
@kingofotaku 
ビルド済みのファイルをメールアドレスに送付しました。
念のため、こちらにもビルド済みのファイルとヘルプのHTMLを添付します。
それでは、よろしくお願いいたします。

I send binary package in this article.
To be on the safe side, I also attach binary package in this article.
Best regards.
[240forTrans.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/4580231/240forTrans.zip)

**Comment by kingofotaku** [comment]
助かります。では、ファイルの翻訳を完成次第メールでお送りしますのでm(_ _)m

**Comment by kingofotaku** [comment]
翻訳済みのファイルをメールでそちらにお送りしました。どうぞご確認ください。

**Comment by Tatsu-syo** [comment]
翻訳ファイルを確認しました。文言については問題ないと思います。
あとは文言以外の軽い調整(ライセンスコメント、HTMLヘルプとしての記述)を当方で行ってリリースしようと思います。
早速の翻訳、ありがとうございました。

**Comment by kingofotaku** [comment]
> 翻訳ファイルを確認しました。文言については問題ないと思います。
> あとは文言以外の軽い調整(ライセンスコメント、HTMLヘルプとしての記述)を当方で行ってリリースしようと思います。
> 早速の翻訳、ありがとうございました。

それは良かったです。実は今回、既存の文言についても何箇所改良しましたので、表現はより正確なものになるではないかと思います。

**Comment by Tatsu-syo** [comment]
皆様へ、本日Meiryo UIも大っきらい!!(No!! Meiryo UI) version 2.40をリリースしました。
ご協力いただき、ありがとうございました。
Thanks to everyone, I am happy to release No!! Meiryo UI Version 2.40.
Thank you for your cooperation.
