### ISSUE TITLE
フォントスタイルのオプションをもっと増やせないでしょうか？

### ISSUE THREAD

**Issue by kingofotaku** [Tatsu-syo/noMeiryoUI#15]
僭越ながら今度はいちユーザーとして提案したいのです。例えば、これはある中国の開発者が作ったフリーウェアですが↓
![TIM截图20200506205105](https://user-images.githubusercontent.com/12953574/81179120-cdb4a800-8fdb-11ea-88d5-47b8a61027c1.png)
![TIM截图20200506205153](https://user-images.githubusercontent.com/12953574/81179145-d6a57980-8fdb-11ea-8765-1d204d19893d.png)

そしてnoMeiryoUIで同じフォントを選ぶとこの通り↓
![TIM截图20200506205902](https://user-images.githubusercontent.com/12953574/81179744-a7433c80-8fdc-11ea-8467-8afb96b5102a.png)

ご覧のように、noMeiryoUIにおいて選べるフォントスタイルは些か少ないのではないかと思います。そこでもしオプションをもっと増やせたら、一層便利になるかと。

**Comment by Tatsu-syo** [comment]
例示されたソフトはどんなソフトで、どこのフォントを操作しているのでしょうか。
太字・細字についてはnoMeiryoUIではフォント名の違いで扱っているので、その分少なくなっているというところはあると思います。
後、色はどのように設定しているのか調査してみないとわからないです。
noMeiryoUIではあくまでWindowsのAPIに従って設定を行っているのですが、他にいじれるところがあるのでしょうか。
Version 2.40は2.40でリリースして、それから調べてみようと思います。Windows 10の大型アップデートも近いですし。

**Comment by kingofotaku** [comment]
すみません、リンク貼るのを忘れました(_ _*)｡こちらです→ https://github.com/zhongyang219/TrafficMonitor
色の変更については（システムUIでは）あまり需要がないと思うので気にしなくても大丈夫です

**Comment by kingofotaku** [comment]
ちなみに、このソフトはシステムのネットトラフィックをモニタリングするソフトで、変更できるフォントはトラフィックとかの数値のところです

**Comment by Tatsu-syo** [comment]
今、コモンダイアログを使っているソフトと比べてみましたが、確かにフォント名とフォントスタイルのまとめ方が異なっていました。
それで、選べるスタイルが少なくなっているように見えるのだと思います。
とはいえ、コモンダイアログのまとめ方だと細字フォントのボールドといった微調整ができないので
フォントはフォントですべて出して、フォントで設定できるスタイルは設定できるようにしたいので敢えてフォントのグループ化をしてスタイルにまとめるというコモンダイアログのまとめ方にはしない方向にしようと思います。
なので、コモンダイアログや例示のソフトと比べると見た目のスタイル数は少なくなっているけどフォントとスタイルのかけ合わせの数では同等という風にしたいと思います。

**Comment by kingofotaku** [comment]
> 今、コモンダイアログを使っているソフトと比べてみましたが、確かにフォント名とフォントスタイルのまとめ方が異なっていました。
> それで、選べるスタイルが少なくなっているように見えるのだと思います。
> とはいえ、コモンダイアログのまとめ方だと細字フォントのボールドといった微調整ができないので
> フォントはフォントですべて出して、フォントで設定できるスタイルは設定できるようにしたいので敢えてフォントのグループ化をしてスタイルにまとめるというコモンダイアログのまとめ方にはしない方向にしようと思います。
> なので、コモンダイアログや例示のソフトと比べると見た目のスタイル数は少なくなっているけどフォントとスタイルのかけ合わせの数では同等という風にしたいと思います。

プログラミングに疎いので専門的な用語はあまりわかりませんけど、つまり今では全体で一つしか表示されないフォントを太さとかの違いによって分けるということですか？

**Comment by Tatsu-syo** [comment]
はい。フォントを太さ等で分けることにしております。
フォントの配布でも太さによって分けて配布している場合もありますので大きな違和感はないと思いますがいかがでしょうか。
また、フォントのグループ化で消える組み合わせの中にも違った見た目になるフォントもあって、カスタマイズ的にも微妙なニュアンスの違いがあって見た目上も興味深いと思ったということもあります(例えば細字フォントのボールド指定とか)。

**Comment by kingofotaku** [comment]
> はい。フォントを太さ等で分けることにしております。
> フォントの配布でも太さによって分けて配布している場合もありますので大きな違和感はないと思いますがいかがでしょうか。
> また、フォントのグループ化で消える組み合わせの中にも違った見た目になるフォントもあって、カスタマイズ的にも微妙なニュアンスの違いがあって見た目上も興味深いと思ったということもあります(例えば細字フォントのボールド指定とか)。

確かにそうですね。フォントによっては、細字をボールド化したものがレギュラーやセミボールドより却っていいっていうこともありますしね。

**Comment by Tatsu-syo** [comment]
では、フォント名とスタイル周りは従来通りで行こうと思います。
人によっても意見は違うと思いますので、クローズはせずに残しておこうと思います。

**Comment by kingofotaku** [comment]
> はい。フォントを太さ等で分けることにしております。
> フォントの配布でも太さによって分けて配布している場合もありますので大きな違和感はないと思いますがいかがでしょうか。
> また、フォントのグループ化で消える組み合わせの中にも違った見た目になるフォントもあって、カスタマイズ的にも微妙なニュアンスの違いがあって見た目上も興味深いと思ったということもあります(例えば細字フォントのボールド指定とか)。

因みに、わたし個人の対処法としてはまずフォント設定をファイルにセーブして、それからそのファイルを編集し、中のWeight=400というデフォルトのパラメータを変更して再ロードするという、間接的な方法でフォントの太さをカスタマイズしています。やや面倒ではありますけど。

**Comment by kingofotaku** [comment]
すいません、今気づいたんですけど、どうやら最初に間違った例示ををしました
![image](https://user-images.githubusercontent.com/12953574/81500502-37e38a80-9305-11ea-8b8c-1b34de47d685.png)
![image](https://user-images.githubusercontent.com/12953574/81500515-4631a680-9305-11ea-9b4c-e49d7c378d56.png)
これが今私が使っている設定なんですけど、見て分かる通り、noMeiryoUIではもともとあるはずのスタイルがないのです（フォント側にもスタイル側にも）。もしこれが最初の例示のように、ただいくつかのフォントに分けられていたらそもそも問題だとは思ってなかったのです（汗）

**Comment by kingofotaku** [comment]
> すいません、今気づいたんですけど、どうやら最初に間違った例示をしたようです
![image](https://user-images.githubusercontent.com/12953574/81500832-5185d180-9307-11ea-860e-a8dab7d960bb.png)
> ![image](https://user-images.githubusercontent.com/12953574/81500739-a4ab5480-9306-11ea-8994-f52640802647.png)
> 
> これが今私が使っている設定なんですけど、見て分かる通り、noMeiryoUIではもともとあるはずのスタイルがないのです（フォント側にもスタイル側にも）。もしこれが最初の例示のようにただいくつかのフォントに分けられていたら、そもそも問題だとは思ってなかったのです（汗）

**Comment by Tatsu-syo** [comment]
フォントを取得するときに取得方法を間違えたのでしょうか。次の週末にでも調べてみようと思います。

**Comment by kingofotaku** [comment]
> フォントを取得するときに取得方法を間違えたのでしょうか。次の週末にでも調べてみようと思います。

お騒がせしてどうもすいませんでしたm(_ _)m

**Comment by Tatsu-syo** [comment]
調べてみたところ、フォントが持っているスタイルを無視してスタイルに斜体、太字の指定を入れていたので違う結果になったようです。
スタイルにはフォントの持っているスタイルを書いて、太字・斜体の修飾は下線・取り消し線と同じようにチェックボックスにするとよい感じになると思います。
ただ、スタイル名についてWindowsのコモンダイアログでは英文フォントのRegularなどは訳していますが、日本語だとそのままダイアログに設定しているという風にバラバラなのでスタイル名についてはフォントが返してきたスタイル名をそのままスタイルに入れるのがよいのかなと思っております。
スケジュールとしては、来週2020年5月31日にリリースするVersion 1.40では従来の方法をとって次のバージョンでスタイル取得方法の見直しを行おうと思います。
このような感じでいかがでしょうか。

**Comment by kingofotaku** [comment]
> 調べてみたところ、フォントが持っているスタイルを無視してスタイルに斜体、太字の指定を入れていたので違う結果になったようです。
> スタイルにはフォントの持っているスタイルを書いて、太字・斜体の修飾は下線・取り消し線と同じようにチェックボックスにするとよい感じになると思います。
> ただ、スタイル名についてWindowsのコモンダイアログでは英文フォントのRegularなどは訳していますが、日本語だとそのままダイアログに設定しているという風にバラバラなのでスタイル名についてはフォントが返してきたスタイル名をそのままスタイルに入れるのがよいのかなと思っております。
> スケジュールとしては、来週2020年5月31日にリリースするVersion 1.40では従来の方法をとって次のバージョンでスタイル取得方法の見直しを行おうと思います。
> このような感じでいかがでしょうか。

はい。こんなマイナーなニーズにわざわざ対応していただき、ほんとにありがとうございますm(_ _)m

**Comment by Tatsu-syo** [comment]
@kingofotaku 
フォント情報の取得方法を見直して、フォント名が同じでフォントのスタイル名だけが異なるフォントを認識できるようにしてみました。(今のところ、フォントの太さ・斜体はオミットしています。)
期待した動きをしますでしょうか。でなければ、フォント名の後ろに太さなどが書いてあるフォントが異なるスタイルのフォントになると思います。
それでは、よろしくお願いいたします。
[241test.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/5259999/241test.zip)

**Comment by kingofotaku** [comment]
> @kingofotaku
> フォント情報の取得方法を見直して、フォント名が同じでフォントのスタイル名だけが異なるフォントを認識できるようにしてみました。(今のところ、フォントの太さ・斜体はオミットしています。)
> 期待した動きをしますでしょうか。でなければ、フォント名の後ろに太さなどが書いてあるフォントが異なるスタイルのフォントになると思います。
> それでは、よろしくお願いいたします。
> [241test.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/5259999/241test.zip)

わざわざありがとうがざいます。試しに実行したところ、こういうふうになっていました。
![image](https://user-images.githubusercontent.com/12953574/93862339-7bf38c80-fcf4-11ea-8bd2-8671ade46aab.png)
前のと比べて、元々なかった細字が出てきました。

**Comment by Tatsu-syo** [comment]
スタイルごとにどうまとめているかなど、まだまだ調整が必要なようなので、週末などに調べてみようと思います。

**Comment by kingofotaku** [comment]
> スタイルごとにどうまとめているかなど、まだまだ調整が必要なようなので、週末などに調べてみようと思います。

ちなみに、私のPCにインストールされているこのフォントのスタイルは英語でいうと、Ultralight、Thin、Ligit、Regular、Medium、Semiboldの6つになります。プログラム上どう扱われるかは知りませんけど、多分そこまで標準的なネーミングじゃないと思います。

**Comment by Tatsu-syo** [comment]
@kingofotaku
だいぶ間が開いてしまいましたが、フォント情報の取得方法を見直して、フォント名・文字セットが同じでフォントのスタイルだけが異なるフォントを認識できるようにしてみました。私のところではフォント名・文字セットが同じでフォントのスタイルだけが異なるフォントを認識しているように見えますが、期待した動きになっていますでしょうか。
今のところ、フォントの太さ・斜体はオミットしています。

ちなみに現状のソースはfontstyleブランチを作ってそこにpushしております。
それでは、よろしくお願いいたします。

[241test2.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/5582503/241test2.zip)

**Comment by kingofotaku** [comment]
![image](https://user-images.githubusercontent.com/12953574/99958963-3a9b5e00-2dc5-11eb-976d-a6020bf0a94e.png)
どうやら今度こそやっと期待していた通りに動いてくれました、計六つのスタイルがすべて検出されるようになりました。作者様本当にご苦労さまです。ありがとうございます。m(_ _)m

**Comment by Tatsu-syo** [comment]
では、これから細かいところとか仕上げていきます。
太字、斜体入れるとか残したままですので。

**Comment by kingofotaku** [comment]
一つ問題というか、状況を発見しました。テストバージョンのSELECTをクリックするとPCの動作がものすごく遅くなるようです。多分スタイル情報の新しい取得方法のせいかと思われます（私はPCに数千ものフォントを入れてます。）

**Comment by Tatsu-syo** [comment]
現在フォント選択ダイアログを表示する際にフォント情報をすべて取得しているのでそれとフォントの数が相まってフォント取得に時間がかかっているのだと思います。
標準のフォントダイアログがどうやっているのかはわかりませんがフォント取得方法を変えることになると思います。

**Comment by kingofotaku** [comment]
> 現在フォント選択ダイアログを表示する際にフォント情報をすべて取得しているのでそれとフォントの数が相まってフォント取得に時間がかかっているのだと思います。
> 
> 標準のフォントダイアログがどうやっているのかはわかりませんがフォント取得方法を変えることになると思います。
> 
> 

まあ、これは仕方ないですね。もっとも私みたいに何千ものフォントを入れる人はそうそういませんから、大した問題じゃないでしょう。

**Comment by Tatsu-syo** [comment]
@kingofotaku 
各フォントの文字セットごとのスタイルをフォントを選択したときに取得するようにしてフォント選択ダイアログ表示時の高速化を図ってみました。
速度的に効果ありますでしょうか。
[241test3.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/5611632/241test3.zip)

**Comment by kingofotaku** [comment]
> @kingofotaku
> 各フォントの文字セットごとのスタイルをフォントを選択したときに取得するようにしてフォント選択ダイアログ表示時の高速化を図ってみました。
> 速度的に効果ありますでしょうか。
> [241test3.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/5611632/241test3.zip)

試してみたところ、効果抜群です！取得速度が現在のバージョンとほぼ同じぐらいになっています。これでこの問題は解決と言っていいと思います。お疲れさまでしたm(_ _)m

**Comment by Tatsu-syo** [comment]
@kingofotaku 
成果を取り込み、スタイル名のローカライズ機構と太字、斜体のオプションをつけたリリース候補版を作成しましたので、新たにissueを立ててこちらでリリースに向けての作業を行いたいと思います。
よってこちらはクローズします。
ご協力ありがとうございました。
