### ISSUE TITLE
About compiling and Packaging

### ISSUE THREAD

**Issue by corgile** [Tatsu-syo/noMeiryoUI#17]
# Hi, I like this font modifier so much, and I hope that a `Makefile` or a windows installer is included  in your releases so people don't have to compile it themselves...  THANK YOU!

**Comment by Tatsu-syo** [comment]
@corgile 
Makefile can't use in No!! Meiryo UI. Because in help file compile , system locale change and reboot.
Windows insataller is not match this project. Because this tool isn't use frequently.
This is why , in release , I use releases. And I release executable file into zip file.

**Comment by corgile** [comment]
thank you
