### ISSUE TITLE
Incomplete replacement on desktop

### ISSUE THREAD

**Issue by Nelson0491** [Tatsu-syo/noMeiryoUI#18]
**Win10 1909 (18363.997)
Home edition**

Edition:
**2.40.1**

font used:
**Sarasa UI SC 9pt** for all

Some problems appear just after starting up, or sometimes during a period of time.

**It seems that some texts are normal, others aren't. I have to refresh the desktop to solve the problem.**
I haven't found other obvious bugs so far.

Screenshots:

![Snipaste_2020-08-05_13-46-19](https://user-images.githubusercontent.com/59787059/89377001-81385000-d723-11ea-9d7a-d3f9a8c2db34.png)

**After refreshing the desktop:**

![Snipaste_2020-08-05_13-47-10a](https://user-images.githubusercontent.com/59787059/89377010-86959a80-d723-11ea-966b-c92b848fddae.png)

I just found that new version 2.40.2 was released days ago. Maybe I' ll try the latest version later.
Anyway, thank you a lot for offering us such a great tool!

**Comment by Tatsu-syo** [comment]
@Nelson0491 
New version 2.40.2 changed Korean language translation only.
Other software may be interfering?
Quit resident software as much as possible, please set fonts again.

**Comment by Nelson0491** [comment]
Sorry I just noticed your reply.
I think it may also relate to many possibilities, like the Win10 system or the processing capacity of the computer, and my computer is a little old.
Anyway, it doesn' t matter a lot. I don't mind the problem so much. It seldom troubles me. (I'm not good at communication, I mean maybe you don't have to spend much time looking for the bug and fixing it. I don't have other unfriendly meanings.)
Thank you for your solution!
