### ISSUE TITLE
中国語簡体字の翻訳は文言がちょっとおかしいようです

### ISSUE THREAD

**Issue by kingofotaku** [Tatsu-syo/noMeiryoUI#2]
自分は（中国人なので）修正できますけど、どうやって修正済みの言語ファイルをそちらに送ればいいですか

**Comment by Tatsu-syo** [comment]
電子メールで送っていただければ次のリリースの際に取り込むようにします。

**Comment by kingofotaku** [comment]
http://nifty.ne.jp メアドはこちらで合ってます？

**Comment by kingofotaku** [comment]
ちなみに、言語ごとに別々のフォントにセットできますか？

**Comment by Tatsu-syo** [comment]
kingofotaku様、はじめまして。No!! Meiryo UI(Meiryo UIも大っきらい!!)
作者のTatsu-syoこと庄子と申します。

メールアドレスはこちらであっておりますので、ご安心ください。
また、フォントについてはFONT_FACE=Systemの=の後ろを変更することで
フォントを変更することができます。

ちなみに、現在の日本語と英語のバージョンアップ履歴を含めたヘルプファイルの
ソースのHTMLはGitHubの方に上げておりますので、こちらもご覧になっていただけると
幸いです。

それでは、失礼します。

On Sat, 14 Apr 2018 10:05:10 -0700
kingofotaku <notifications@github.com> wrote:

> ちなみに、言語ごとに別々のフォントにセットできますか？
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatsu-syo/noMeiryoUI/issues/2#issuecomment-381343899


-- 
庄子 達彦(Tatsu)
E-mail Address rxk16664@nifty.ne.jp
My Web page http://tatsu.life.coocan.jp/index.html

**Comment by kingofotaku** [comment]
ヘルプファイルについては、また暇ができたらチェックしますので(^^)

**Comment by Tatsu-syo** [comment]
これまで、簡体字中国語訳を行っていただいた方にもチェックをしていただいて、共著という形で出そうと思いますが、いかがでしょうか。

**Comment by Tatsu-syo** [comment]
これまで、簡体字中国語訳を行っていただいた方のチェックも通りましたが、ヘルプの部分の語句が古いままということに気づきましたので、語句を入れ替えさせていただきました。

**Comment by Tatsu-syo** [comment]
ヘルプの著者表記を各国語版のヘルプに追加して、翻訳、ヘルプとも完成としましたのでこれにてリリースします。
