### ISSUE TITLE
Could you please add an additional function~^~

### ISSUE THREAD

**Issue by ComeOrDream** [Tatsu-syo/noMeiryoUI#20]
In Windows 10, the font of the menu cannot be modified, as well as the option page. I am sincerely looking forward to the new function.

**Comment by Tatsu-syo** [comment]
Which menu do you want to change font?
No!! Meiryo UI is basically system font change tool.
Option page don't see system font settings.
I can't change option page's font. Sorry.

**Comment by ComeOrDream** [comment]
Sorry, these pages are what I talk about.
![2020-09-15_071801](https://user-images.githubusercontent.com/43801479/93147463-d6548200-f723-11ea-94fd-acdbc9c14a85.png)
![2020-09-15_071829](https://user-images.githubusercontent.com/43801479/93147467-db193600-f723-11ea-81fa-d70f47a7f8cc.png)

**Comment by YsHaNgM** [comment]
They are not win32 programs I suppose. They use xaml config UI.

**Comment by Tatsu-syo** [comment]
For UWP UI, this software take no effects. Close it.
