### ISSUE TITLE
To release version 2.41

### ISSUE THREAD

**Issue by Tatsu-syo** [Tatsu-syo/noMeiryoUI#21]
@asthzh @kingofotaku 

Today(12/6/2020), I made No!! Meiryo UI version 2.41 execute file.
I have plan to release version 2.41 on 12/27/2020 or 1/10/2021.
To release, language fileｓ and help files need to be translated.
If you can help me, please translate language fileｓ and help files.

Language fileｓ Translation point is below.
DLG_CHECK_BOLD=&Bold
DLG_CHECK_ITALIC=&Italic
DLG_STYLE_MEDIUM=Medium
DLG_STYLE_SEMI_BOLD=Semibold
DLG_STYLE_BOOK=Book
DLG_STYLE_OBLIQUE=Oblique
DLG_STYLE_LIGHT=Light
DLG_STYLE_EXTRA_LIGHT=ExtraLight
DLG_STYLE_SEMI_LIGHT=SemiLight
DLG_STYLE_SLANTED=Slanted

To translate, you can use translators package
[241forTrans.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/5648678/241forTrans.zip)
or master branch.

Best regards.

**Comment by kingofotaku** [comment]
[noMeiryoUI.zip](https://github.com/Tatsu-syo/noMeiryoUI/files/5664394/noMeiryoUI.zip)
PRのやり方がよくわからないので、直接アップロードさせていただきました。

**Comment by Tatsu-syo** [comment]
@kingofotaku 
Thank you for your cooperation.
Everything is OK.
I merge all files.

----
ご協力ありがとうございます。
すべて問題ありません。
早速ファイルを取り込みました。
