### ISSUE TITLE
字体无法全部恢复

### ISSUE THREAD

**Issue by yinuan-i** [Tatsu-syo/noMeiryoUI#22]
使用完后，想要恢复，安装软件上恢复win10 ，还是有一部分字体恢复不了，比如，一些浏览器显示的内容，软件里的内容

**Comment by Tatsu-syo** [comment]
@yinuan-i 
Sorry to late response.
Please try font size change or display language reset.
Or some action to reset system fonts.

**Comment by YsHaNgM** [comment]
Font cache is not updated unless you restart a window session. If you see fonts remain unchanged in Windows multi-task or taskbar you can try to restart explorer `Stop-Process -ProcessName explorer`. If it's some programs, try close the window and reopen them. It works for me most of times.
