### ISSUE TITLE
noMeiryoUI的工作原理是替换（微软雅黑=替换的字体）还是修改（修改配置文件，字体不受影响）？

### ISSUE THREAD

**Issue by billowssun** [Tatsu-syo/noMeiryoUI#28]

**Comment by Tatsu-syo** [comment]
No!! MeiryoUI don't modify font file.
No!! MeiryoUI set Windows system font settings as Windows 7.

**Comment by Desomnd** [comment]
这个软件通过对Win7开始存在的字体配置文件进行更改。

**Comment by Tatsu-syo** [comment]
Ok, close issue.
