### ISSUE TITLE
Font size changes after using monitor with different DPI

### ISSUE THREAD

**Issue by YsHaNgM** [Tatsu-syo/noMeiryoUI#30]
I use a script to set font, it reads setting file. It sometimes sets fonts into 6pt or 18pt after swapping external monitor. My laptop has 4k 13 inch screen, if I plug in an enternal 1080p 24 inch monitor and restart, No!!Meiryo shows fonts are 18pt. If I restart with a 4k 24 inch monitor connectted, No!!Meiryo shows font size 6pt or vice versa. This makes my script not usable at all, I have to adjust fonts size to 9pt in UI each time, otherwise they are extremely large or small.

**Comment by Tatsu-syo** [comment]
No!! Meiryo UI's setting file has font size by pixels.
And, on start up No!! Meiryo UI set font size by pixels without monitor DPI.
This is why.
To solve this problem, No!! Meityo UI records font size by points.
I'm plannning to solve this issue when next version to Windows 11 adaption.

**Comment by entr0pia** [comment]
I ran into the same problem and looked forward to the solution.

**Comment by Tatsu-syo** [comment]
In version 3.0.0 I changed to save font size by points.
Please try it.

**Comment by YsHaNgM** [comment]
Trojan:Script/Wacatac.B!ml found by Windows security when open 3.0.0RC1. Do I need to worry about it? Can you check your build environment and submit a false alarm ticket to Microsoft if there's nothing wrong?

**Comment by Tatsu-syo** [comment]
Hmm, false positive ?
I builg it Visual  Studio  2019 compiler.
If you can, submit  it to vendor .
And try again after some  days.
I think you don't  worry about  it.
> Trojan:Script/Wacatac.B!ml found by Windows security when open 3.0.0RC1. Do I need to worry about it? Can you check your build environment and submit a false alarm ticket to Microsoft if there's nothing wrong?

**Comment by Tatsu-syo** [comment]
It seems to be there is no problem in Visual Studio 2008. Close issue.
