### ISSUE TITLE
Seems doesn't work in Win11?

### ISSUE THREAD

**Issue by zerosherd** [Tatsu-syo/noMeiryoUI#32]
Could you please fit the Win11, i am in the latest Windows 11 dev Channel.

**Comment by Tatsu-syo** [comment]
I don't follow Windows 11 dev Channel.
What is happening?

**Comment by Tatsu-syo** [comment]
What font are you trying to change?
No!! Meiryo UI changes system font settings.
System font settings effects programs such as Win32 WinForm programs.
