### ISSUE TITLE
Title bars became extremely large after I changed the system font on Windows 11

### ISSUE THREAD

**Issue by LucidLoli** [Tatsu-syo/noMeiryoUI#34]
ウインドーのタイトルバーが余計に大きくなってしまいました。文字はそんなに大きくありませんのに。OSのせいでしょうか。😢

![screenshot](https://user-images.githubusercontent.com/96704771/150638944-621356de-52b1-4fcb-bd7a-66b15e75636f.png)

OS: Windows 11 Pro Insider Preview Dev, Build 22538
No!! Meiryo UI Version: 2.42、releaseページで公開された実行ファイル。
My Language: 簡体中国語

**Comment by Tatsu-syo** [comment]
Did you change large font size previously?
No!! Meiryo UI don't change title bar size.
To recover, use Re-Metrics(https://github.com/Tatsu-syo/ReMetrics).
If you occur some trouble, please reply this issue.

**Comment by LucidLoli** [comment]
はい。No!! Meiryo UI を使う前にパソコンの設定で字体を大きくしたことが有ります。親切にして下さって有難う御座います！😊
