### ISSUE TITLE
The 3.0.0 download file might be contaminated by a Trojan

### ISSUE THREAD

**Issue by srozanski60** [Tatsu-syo/noMeiryoUI#38]
When I was downloading the 3.0.0 file my windows defender found a threat
Script/Phonzy.B!ml

![微信截图_20220214175105](https://user-images.githubusercontent.com/81260800/153960032-2a3f9156-a508-4770-ae93-408b38ef7eae.png)

Please check if you have this issue. Thanks.

**Comment by Tatsu-syo** [comment]
In my PC with ESET, it didn't occured.
I checked in VirusTotal, several anti virus software flagged program file as malicious.
In version 3.0.0, I changed compiler to Visual Studio 2019's C++ compiler.
Before version 2.41, I use Visual Studio 2008's C++ compiler, and didn't flagged.
I compile version 3.0.0's source file by Visual Studio 2008's C++ compiler, program didn't flagged.
Probably, Visual Studio 2019's C++ compiler and runtime library cause it.

To solve this problem, I changed the archive executable to one compiled with Visual Studio 2008's C++ compiler. And uploaded it again.

Please download again.
Thank you for your report.

Why Visual Studio 2019's C++ compiler and runtime library cause it? I don't understand.

**Comment by srozanski60** [comment]
Thanks for your reply. There is no warning now. Thanks!

**Comment by Tatsu-syo** [comment]
I added notice about this issue on release page,

**Comment by win98se** [comment]
To prevent future occurances, you can try to submit the program for clarification as a home customer and a software developer respectively at [microsoft.com/en-us/wdsi/filesubmission](https://www.microsoft.com/en-us/wdsi/filesubmission) once it happens again.

Macrohard shall not mark it as a trojan anymore, as it is a false positive and does not harm Windows in any way.

**Comment by Tatsu-syo** [comment]
Thank you for instructing me in this page.
In next release, I test Visual Studio 2022 build and 2008 build.

**Comment by Tatsu-syo** [comment]
In Visual Studio 2008 build, it seems to be no problem. Close this issue.
