### ISSUE TITLE
Could you please support windows 7?

### ISSUE THREAD

**Issue by kratoskang** [Tatsu-syo/noMeiryoUI#4]
Thanks.

**Comment by Tatsu-syo** [comment]
No! MeiryoUI!! also supports Windows 7.
But there is no mean to run on Windows 7.
Because Windows 7 has system font setting dialog.

**Comment by Tatsu-syo** [comment]
There is no reply. And No! MeiryoUI!! supports Windows 7.
This is why, I close this issue.
