### ISSUE TITLE
Windows 10 1903 Professional Font Explode Affter Use noMeiryoUI 3.0.0.

### ISSUE THREAD

**Issue by 318cyz** [Tatsu-syo/noMeiryoUI#43]
I set the font to "汉仪南宫体简   9pt",and a lot of word show non-"汉仪南宫体简   9pt" font.
even some are s8514sys.fon.
Please help me.

**Comment by Tatsu-syo** [comment]
Use 恢复系统默认字体 to restore initial settings.
If trouble still occurres, once change another display language, and your native language again.

**Comment by 318cyz** [comment]
I fixed these lost files by ESD upgrade patch. Thank you.
