### ISSUE TITLE
Bug report: How can I deal with this?

### ISSUE THREAD

**Issue by ShyAaZz** [Tatsu-syo/noMeiryoUI#5]
[Bug Screenshot.png](https://pic2.zhimg.com/v2-5736b0c3f4c9213a6668918366d490e5_b.png)
Set all system fonts to 72pt, and turn back to 9pt.
Then my Title Bar have been destroyed by this Bug.
---
No!! Meiryo UI Version 2.35  
Windows 10 Home Edition 1803 Build 17134.765

**Comment by Tatsu-syo** [comment]
Use Re-Metrics (available on http://tatsu.life.coocan.jp/MySoft/WinCust/index.html).
Re-Metrics can set title bar size.

**Comment by icebeam030** [comment]
Actually this bug is also reproducible when using 1903 and later Windows 10, when you change system DPI, text enlarging option in accessibility settings, and use noMeiryoUI to sent font size.

**Comment by Tatsu-syo** [comment]
I released Re-Metrics (available on http://tatsu.life.coocan.jp/MySoft/WinCust/index.html) new version.
This version contains English translations.
Please use it.
