### ISSUE TITLE
Title bar being transparent in Windows11 22622.575

### ISSUE THREAD

**Issue by StandardL** [Tatsu-syo/noMeiryoUI#51]
In traditional windows, title bar got transparent. But it's ok when using win11sytle windows.
![image](https://user-images.githubusercontent.com/91111027/184765884-0d57c2b8-7e9e-4cca-ad05-31dd6a8aad32.png)
![image](https://user-images.githubusercontent.com/91111027/184766163-0b654780-befc-45f1-bfba-71b3189087aa.png)
![image](https://user-images.githubusercontent.com/91111027/184766443-bb63276c-220c-4934-914b-edae20a5af71.png)
![image](https://user-images.githubusercontent.com/91111027/184767129-7be9e65f-a638-49ac-9dc9-19ff2881bf11.png)

**Comment by Tatsu-syo** [comment]
Hmm, Windows visual change causes this trouble?
Block title bar change? Or add warning message and use own risk?
I will try on Windows 11 22H2 official release version, and decide what to do.
Thank you for your report with screen shot.

**Comment by StandardL** [comment]
Oh, I find a way to avoid it. When I set default font in title bar, all title bar runs perfectly.
![image](https://user-images.githubusercontent.com/91111027/188294170-6e14b985-af94-490a-8288-0097e85ee6d1.png)
![image](https://user-images.githubusercontent.com/91111027/188294181-4eaa3c5a-d3c1-408a-b7c5-10fd6fc76248.png)
![image](https://user-images.githubusercontent.com/91111027/188294197-1aef11f8-41e1-4aca-9a45-7a994ee9791c.png)

**Comment by Tatsu-syo** [comment]
Hmmm, when running on Windows 11 2022, should I disable the font change in the title bar?
Some news reported Windows 11 2022 will be released Sep. 20.
Should I prepare by this way?

**Comment by StandardL** [comment]
Yep, I think it's a good choice. Also, when user trys to change the font in title bar, the program should give a warning message.

**Comment by Tatsu-syo** [comment]
Another way, ignore title bar font change act.

**Comment by jarupxx** [comment]
It happens with certain fonts, but most fonts are no issue the title bar. Personally, I would prefer to be able to change the title bar font.

**Comment by Tatsu-syo** [comment]
Hmm, What fonts cause troubles and what fonts don't cause troubles?
I tested as far as my 22H2 22621.382, European language fonts are OK, but fonts which have Asian languages are NG.
It seems MS engineers didn't care Asian languages. It's too bad! bad! bad!
Let's calm down.
I use Japanese version Windows 11 22H2 and encounter title bar trouble.
And No!! Meiryo UI is used many east asian peoples in Japan, China, Korea, Taiwan.
If these features are missing, many people encounter trouble, I will spend many time to answer to tell how to solve trouble.
This is why, warning message and guards are required.
Please understand.

**Comment by Tatsu-syo** [comment]
I think add command line option to kill title bar font change blocker.
If users can unlock blocker from GUI, I think some users use unlock switch without unintentionally and cause trouble.
For example, I sometime receive report user change font size very large, and title bar become too thick.
This is why, if I add title bar font change unlock switch, I add this by command line.

By the way, I implement some undocumented command line switch.
See source file.
I really dislike Meiryo UI :)

**Comment by jarupxx** [comment]
Understood. Thank you.

Here are the results of my research.

I tested with Japanese 22H2 22621.521.
Font Initials with A to F.
Defect occurred at 5/103.
transparent Title bar
    ADMUI3Lg
    ADMUI3Sm
    Courier
    FixedSys
Title bar become too thick
    Cambria Math

To restore the Title bar become too thick, increase the scaling settings on Windows and do rebooting.
Display Settings > Scaling and Layout > Zoom In/Zoom Out (100% > 125%, 150% > 175%, etc.)

**Comment by Tatsu-syo** [comment]
CJK fonts and bitmap font?
Thank you for telling title bar tips.

**Comment by jarupxx** [comment]
Yes, bitmap fonts. Not affected by character set.
OS standard fonts:
.ttc and .ttf are not transparent. bitmap fonts (.fon) are transparent.
Third-party fonts:
.otf will be transparent. Some fons even .ttf become transparent (VLGothic-20220612).
