### ISSUE TITLE
NoMeiryoUI is not applied to Shell's photon

### ISSUE THREAD

**Issue by MyAlfisti** [Tatsu-syo/noMeiryoUI#57]
### NoMeiryoUI is not applied to Shell's photon
In Explorer, the fonts can be specified and displayed very beautifully.
However, this does not apply to the start menu, context menu, widget sidebar, etc.
Is this a noMeiryoUI specification?

**Comment by Tatsu-syo** [comment]
Yes.
Start menu, context menu, widget sidebar, etc don't use system font settings.
Japanese version is really dull.
