### ISSUE TITLE
Next Version 2.36 help translation

### ISSUE THREAD

**Issue by Tatsu-syo** [Tatsu-syo/noMeiryoUI#6]
@devbug message_content
@kingofotaku  message_content

現在、Version 2.36リリースに向けて準備を進めております。
変更点は、

- 一括設定ボタンを押したときもアプリケーションを終了するようにしました。
- ブラジルのポルトガル語訳を追加しました。(予定)
- Version 2.35で入れ忘れていた簡体字中国語訳を入れました。

となります。現在日本語と英語のヘルプの訳がある状態なので、残りは簡体字中国語と韓国語となります。
よろしくお願いいたします。

I prepare to next release version 2.36.
Changes is below.

- Exit application after Set all fonts.</li>
- Add Brazilian Portuguese translation.</li>
- Included Chinese translation that was forgotten on Version 2.35.

Please translate Simplified Chinese and Korian release note.
Best regards.

**Comment by kingofotaku** [comment]
つまりヘルプファイルを訳せばいいということですか？

**Comment by Tatsu-syo** [comment]
kingofotaku様、ごぶさたしております。
Tatsuこと庄子です。

> つまりヘルプファイルを訳せばいいということですか？
はい、Version 2.36の変更点とポルトガル語(ブラジル)の作者表記になります。

それでは、よろしくお願いいたします。

On Sat, 14 Dec 2019 21:26:57 -0800
kingofotaku <notifications@github.com> wrote:

> つまりヘルプファイルを訳せばいいということですか？
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatsu-syo/noMeiryoUI/issues/6#issuecomment-565779537


-- 
庄子 達彦(Tatsu)
E-mail Address rxk16664@nifty.ne.jp
My Web page http://tatsu.life.coocan.jp/index.html

**Comment by kingofotaku** [comment]
> kingofotaku様、ごぶさたしております。 Tatsuこと庄子です。
> つまりヘルプファイルを訳せばいいということですか？
> はい、Version 2.36の変更点とポルトガル語(ブラジル)の作者表記になります。 それでは、よろしくお願いいたします。
> […](#)
> On Sat, 14 Dec 2019 21:26:57 -0800 kingofotaku ***@***.***> wrote: つまりヘルプファイルを訳せばいいということですか？ -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#6 (comment)](https://github.com/Tatsu-syo/noMeiryoUI/issues/6#issuecomment-565779537)
> -- 庄子 達彦(Tatsu) E-mail Address rxk16664@nifty.ne.jp My Web page http://tatsu.life.coocan.jp/index.html

わかりました。あと、完成したファイルをどうすればいいんでしょうか？メールでそちらに送ればいいんですか？

**Comment by Tatsu-syo** [comment]
こんばんは、Tatsuこと庄子です。

完成したファイルについてはメールでも、GithubのPull requestでもどちらでも
OKです。

それでは、よろしくお願いいたします。

On Sat, 14 Dec 2019 21:43:21 -0800
kingofotaku <notifications@github.com> wrote:

> > kingofotaku様、ごぶさたしております。 Tatsuこと庄子です。
> > つまりヘルプファイルを訳せばいいということですか？
> > はい、Version 2.36の変更点とポルトガル語(ブラジル)の作者表記になります。 それでは、よろしくお願いいたします。
> > […](#)
> > On Sat, 14 Dec 2019 21:26:57 -0800 kingofotaku ***@***.***> wrote: つまりヘルプファイルを訳せばいいということですか？ -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#6 (comment)](https://github.com/Tatsu-syo/noMeiryoUI/issues/6#issuecomment-565779537)
> > -- 庄子 達彦(Tatsu) E-mail Address rxk16664@nifty.ne.jp My Web page http://tatsu.life.coocan.jp/index.html
> 
> わかりました。あと、完成したファイルをどうすればいいんでしょうか？メールでそちらに送ればいいんですか？
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatsu-syo/noMeiryoUI/issues/6#issuecomment-565780264


-- 
庄子 達彦(Tatsu)
E-mail Address rxk16664@nifty.ne.jp
My Web page http://tatsu.life.coocan.jp/index.html

**Comment by kingofotaku** [comment]
> こんばんは、Tatsuこと庄子です。 完成したファイルについてはメールでも、GithubのPull requestでもどちらでも OKです。 それでは、よろしくお願いいたします。 On Sat, 14 Dec 2019 21:43:21 -0800 kingofotaku <notifications@github.com> wrote:
> […](#)
> > kingofotaku様、ごぶさたしております。 Tatsuこと庄子です。 > つまりヘルプファイルを訳せばいいということですか？ > はい、Version 2.36の変更点とポルトガル語(ブラジル)の作者表記になります。 それでは、よろしくお願いいたします。 > […](#) > On Sat, 14 Dec 2019 21:26:57 -0800 kingofotaku ***@***.***> wrote: つまりヘルプファイルを訳せばいいということですか？ -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#6 (comment)]([#6 (comment)](https://github.com/Tatsu-syo/noMeiryoUI/issues/6#issuecomment-565779537)) > -- 庄子 達彦(Tatsu) E-mail Address ***@***.*** My Web page http://tatsu.life.coocan.jp/index.html わかりました。あと、完成したファイルをどうすればいいんでしょうか？メールでそちらに送ればいいんですか？ -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#6 (comment)](https://github.com/Tatsu-syo/noMeiryoUI/issues/6#issuecomment-565780264)
> -- 庄子 達彦(Tatsu) E-mail Address rxk16664@nifty.ne.jp My Web page http://tatsu.life.coocan.jp/index.html

わかりました。では、完成し次第Pull requestしてみます。

**Comment by icebeam030** [comment]
I will do a SC translation based on your English release notes:

- Exit application after Set all fonts.
- Add Brazilian Portuguese translation.
- Included Chinese translation that was forgotten on Version 2.35.

- 现在在设定所有字体后程序会自动关闭
- 增加了巴西葡萄牙语翻译
- 加入了2.35版中遗忘的中文翻译

**Comment by Tatsu-syo** [comment]
@kingofotaku 
こちらの訳はいかがでしょうか。あと、中国語ではポルトガル語(ブラジル)はどのように書くのでしょうか。
How about this translation. And, How do you write Portuguese (Brazil) in Chinese?

**Comment by kingofotaku** [comment]
> @kingofotaku
> こちらの訳はいかがでしょうか。あと、中国語ではポルトガル語(ブラジル)はどのように書くのでしょうか。
> How about this translation. And, How do you write Portuguese (Brazil) in Chinese?

ちょうど時間の都合で変更履歴を割愛しましたので助かります。ただ、「加入了2.35版中遗忘的中文翻译」というのは「ｖ2.35でやり残していた中国語翻訳を導入しました」っていう意味です。しかしｖ2.35ではすでにプログラム自体の翻訳は完成していたのでは？

**Comment by Tatsu-syo** [comment]
@kingofotaku
V2.35の時に、アーカイブに入れ忘れていたのでそのフォローになります。完全に私のミスです。申し訳ありませんでした。ちなみに今はWebページとベクターには修正版のアーカイブを出しております。

**Comment by kingofotaku** [comment]
> @kingofotaku
> V2.35の時に、アーカイブに入れ忘れていたのでそのフォローになります。完全に私のミスです。申し訳ありませんでした。ちなみに今はWebページとベクターには修正版のアーカイブを出しております。

なるほど、わかりました。そういうことでしたら問題ありません。

**Comment by kingofotaku** [comment]
また、改めてそちらのメールアドレスにメールを送りました。先程自分のミスでうっかりPull requestのファイルを間違えました。ですので今度はメールで正しいファイルをそちらに送りました。どうもすいませんm(_ _)m

**Comment by Tatsu-syo** [comment]
細かな、訳の改良ありがとうございます。こちらの方をさっそく使わせていただきます。

**Comment by kingofotaku** [comment]
> 細かな、訳の改良ありがとうございます。こちらの方をさっそく使わせていただきます。

一度確認しますけど、メールの方のファイルですよね？

**Comment by kingofotaku** [comment]
> I will do a SC translation based on your English release notes:
> 
> * Exit application after Set all fonts.
> * Add Brazilian Portuguese translation.
> * Included Chinese translation that was forgotten on Version 2.35.
> * 现在在设定全部字体后程序会自动关闭
> * 增加了巴西葡萄牙语翻译
> * 加入了2.35版中遗忘的中文翻译

感谢这位朋友提供翻译。

**Comment by Tatsu-syo** [comment]
@kingofotaku 
はい、メールの方のファイルになります。
あと、icebeam030 様のリリースノートの訳を合わせて、取りまとめようと思います。

**Comment by kingofotaku** [comment]
> @kingofotaku
> はい、メールの方のファイルになります。
> あと、icebeam030 様のリリースノートの訳を合わせて、取りまとめようと思います。

わかりました。新しいバージョンに期待しています。自分も長い間このソフトを愛用していますので、再びに貢献できて嬉しいです。

**Comment by Tatsu-syo** [comment]
@devbug message_content
韓国語のリリースノートについてですが、これ以上リリースを遅らせるのも他の方に悪いので、1月4日あたりを目処にリリースノートが来ない場合はリリースノートなしでリリースしようと思っております。他の方も含めていかがでしょうか。
If the Korean release notes aren't come in 1/5, I'm considering releasing them without the Korean release notes.

**Comment by kingofotaku** [comment]
私は賛成します。リリースノートやヘルプファイル等より、ソフト本体の改善が重要だと思います。

**Comment by Tatsu-syo** [comment]
Thanks to @austin-chang , on next version I will release with Traditional Chinese language file.
What is the spelling of Simplified Chinese in Traditional Chinese?
@kingofotaku @icebeam030

**Comment by kingofotaku** [comment]
> 
> 
> Thanks to @austin-chang , on next version I will release with Traditional Chinese language file.
> What is the spelling of Simplified Chinese in Traditional Chinese?
> @kingofotaku @icebeam030

簡體中文

**Comment by Tatsu-syo** [comment]
Sorry, It was the opposite.
What is the spelling of Traditional Chinese in Simplified Chinese?
@kingofotaku @icebeam030

**Comment by kingofotaku** [comment]
> 
> 
> Sorry, It was the opposite.
> What is the spelling of Traditional Chinese in Simplified Chinese?
> @kingofotaku @icebeam030

正体中文

**Comment by Tatsu-syo** [comment]
Thanks.
I will release No!! Meiryo UI in 1/13.

**Comment by icebeam030** [comment]
Confirming the translation is correct.
BTW, do you plan to fix the bug that improper window metrics settings can be applied in some cases?
Or maybe at least you want to add more language options to your other software that deals with this issue?

**Comment by Tatsu-syo** [comment]
@icebeam030 I'm planning to make another small software that restores initial fonts and metrics.
For example, some people likes narrow title bar. But, other people may prefer a thick title bar.
Such issue, it's suitable for my another product Re-Metrics.
But, I any number of times received suggestions that after restore setting bigger font size(ex.72pt->12pt) it's difficult to reset title bar size(for example, issue #5).
I think this requires two pieces of software.
This is why, I think to make small all-in-one reset tool.

**Comment by icebeam030** [comment]
Makes sense. I am just saying that Re-Metrics is Japanese only so maybe you should at least add English language file to it.

**Comment by Tatsu-syo** [comment]
It's only complexity problems.
If I ｃonsolidate No!! Meiryo UI and Re-Metrics, program and user interface become more complex.
And amount of translation increases.
This is why, I sepalete No!! Meiryo UI and Re-Metrics.

**Comment by Tatsu-syo** [comment]
This issue is opening for next version of No!! Meiryo UI.
When I release No!! Meiryo UI version 2.36, I will close this issue.
If you have opinion for future version, please open new issue.

**Comment by Tatsu-syo** [comment]
Today(Jan 13), I released No!! Meiryo UI version 2.36 released.
Thank you very much for all.
