### ISSUE TITLE
After the font setting a weird window appears behind the visual studio's startup window

### ISSUE THREAD

**Issue by YGaotian** [Tatsu-syo/noMeiryoUI#61]
![屏幕截图 2022-11-29 152329](https://user-images.githubusercontent.com/101716740/204464886-92fa18fb-f34f-488c-a76a-62b1df8744d9.png)
As you can see, there is an ugly window under the visual studio's startup window after I use NO!!Meiryo UI, so I guess perhaps it's because noMeiryoUI changed some system files or registry or something else? I wonder how I can UNDO the font settings or just disable the effect of noMeiryoUI because I have already reset the system default font through the NO!!Meiryo UI, but it didn't solve my problem. Well if my guess is wrong and the problem is not caused by noMeiryoUI, I apologize!

**Comment by LKoiJZ** [comment]
我也出现了相同的问题，表现在steam++上

**Comment by Tatsu-syo** [comment]
I know steam++ when I see this reply.
steam++ uses .NET Framework and WPF.
WPF can use programmer's specify font.
And I think it looks like programmer specify own font.
Please contact steam++ author.

**Comment by LKoiJZ** [comment]
明白，我会尝试将问题反馈给steam++作者

**Comment by YGaotian** [comment]
This issue now can be solved by using the method from #64 
Thank @digiant
