### ISSUE TITLE
这个工具会让win11 22h2的UI显示异常

### ISSUE THREAD

**Issue by liyuhaolol** [Tatsu-syo/noMeiryoUI#65]
每设置一次字体，窗口右上角的关闭、最小化，最大化3个按钮都会变大一次，这是一个非常恶性的BUG，希望作者可以尽快修正此问题，现在本工具在win11 22h2上是完全不可用状态。

Each time the font is set, the three buttons on the top right corner of the window, Close, Minimize, and Maximize, will become larger. This is a very vicious bug. I hope the author can correct this problem as soon as possible. Now this tool is completely unavailable on win11 22h2.

![deb41087e950352afcfc11674443fbf2b3118b83](https://user-images.githubusercontent.com/16422963/212523273-404a89ea-7c12-4979-aa5d-9aff24502e83.jpg)

出现这个问题需要用下面的reg进行恢复，恢复后设置的字体也会恢复为系统默认字体

If this problem occurs, you need to use the following reg to restore. After restoring, the font set will also be restored to the system default font

```
Windows Registry Editor Version 5.00


[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
"BorderWidth"="-15"
"CaptionFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
00,00,00,01,00,00,05,00,4d,00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,74,\
00,20,00,59,00,61,00,48,00,65,00,69,00,20,00,55,00,49,00,00,00,00,00,00,00,\
00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"CaptionHeight"="-330"
"CaptionWidth"="-330"
"IconFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,00,\
00,00,01,00,00,05,00,4d,00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,74,00,\
20,00,59,00,61,00,48,00,65,00,69,00,20,00,55,00,49,00,00,00,00,00,00,00,00,\
00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"IconTitleWrap"="1"
"MenuFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,00,\
00,00,01,00,00,05,00,4d,00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,74,00,\
20,00,59,00,61,00,48,00,65,00,69,00,20,00,55,00,49,00,00,00,00,00,00,00,00,\
00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"MenuHeight"="-285"
"MenuWidth"="-285"
"MessageFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
00,00,00,01,00,00,05,00,4d,00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,74,\
00,20,00,59,00,61,00,48,00,65,00,69,00,20,00,55,00,49,00,00,00,00,00,00,00,\
00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"ScrollHeight"="-255"
"ScrollWidth"="-255"
"Shell Icon Size"="32"
"SmCaptionFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,\
00,00,00,00,01,00,00,05,00,4d,00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,\
74,00,20,00,59,00,61,00,48,00,65,00,69,00,20,00,55,00,49,00,00,00,00,00,00,\
00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"SmCaptionHeight"="-330"
"SmCaptionWidth"="-330"
"StatusFont"=hex:f4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
00,00,00,01,00,00,05,00,4d,00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,74,\
00,20,00,59,00,61,00,48,00,65,00,69,00,20,00,55,00,49,00,00,00,00,00,00,00,\
00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"PaddedBorderWidth"="-60"
"AppliedDPI"=dword:00000060
"IconSpacing"="-1130"
"IconVerticalSpacing"="-1130"
"MinAnimate"="1"
```

**Comment by Tatsu-syo** [comment]
Hmm, how many size did you set?
I can't reproduce this issue.

**Comment by liyuhaolol** [comment]
> Hmm, how many size did you set? I can't reproduce this issue.

i use 27 inch 4k ,150% scale, 110% font scale, i remamber font size is 10 in noMeiryoUI ,default is 9

**Comment by Tatsu-syo** [comment]
I make [Version 3.1.1 test 1](https://github.com/Tatsu-syo/noMeiryoUI/releases/tag/TAG-3.1.1_test1).
On this version, when set font settings, change title bar size using font size.

Please test this.

**Comment by lanzhiquan** [comment]
> 

It looks weird on 200% DPI scale, ...too narrow.

**Comment by lanzhiquan** [comment]
> I make [Version 3.1.1 test 1](https://github.com/Tatsu-syo/noMeiryoUI/releases/tag/TAG-3.1.1_test1). On this version, when set font settings, change title bar size using font size.
> 
> Please test this.

It looks weird on 200% DPI scale, ...too narrow.

**Comment by hoiyuyiu** [comment]
你可以试试他的另一个软件，似乎是调整窗口UI用的，叫Re-Metrics，可以调整按钮和标题栏大小，不知道具体怎么调用预设里的win11好像就行
