### ISSUE TITLE
Windows 11にてフォント変更後メモ帳の枠が白くしまってしまう問題

### ISSUE THREAD

**Issue by kako774** [Tatsu-syo/noMeiryoUI#69]
Windows 11環境でメモ帳の枠が白くしまってしまう問題について過去のIssueにも報告が上がっており、実際に確認しましたが、

どうやら以下のレジストリの変更が原因のようです (Windows 11のみ影響が出ます)
HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetricsの
PaddedBorderWidthキーが-60(既定値)から0になったのが原因と思われます。

フォント変更時にPaddedBorderWidthキーを変更しないように修正していただくことは可能ですか？
ウィンドウ枠の幅のキーなのでフォント変更には影響ないのは確認しました。

**Comment by Tatsu-syo** [comment]
Thanks.
I have another problem about WindowMetrics.
I will check code about WindowMetrics.

**Comment by Tatsu-syo** [comment]
This issue is same as #64.
I will discussion on #64 and this issue mark closed.

**Comment by kako774** [comment]
Thank you.
