### ISSUE TITLE
The update log missed writing

### ISSUE THREAD

**Issue by HSSadBoy** [Tatsu-syo/noMeiryoUI#80]
In Version 3.2.1.1, There are no issues with updating logs. But in version 3.2.1,  It seems that there is a repair for both Chinese Simplified and Chinese Traditional, isn't it explicitly stated?

**Comment by HSSadBoy** [comment]
What I mean is that there is no content about Chinese Traditional and Chinese Simplified in the update log at 3.2.1

**Comment by Tatsu-syo** [comment]
In 3.2.1,　some Simplified Chinese(China) mixed with Traditional Chinese(Taiwan) translations.
I received pull request in @abc0922001 , and I judged it was serious problem for Taiwan users, and decided to release it rapidly, This is reason to release 3.2.1.1.

About release note  I can't speak Chinese, I can't update log in Chinese. So, release log is depended on translators.
This is why, there is no content about Chinese Traditional and Chinese Simplified in the update log at 3.2.1.
On Japanese and English release note have content about Chinese Traditional and Chinese Simplified in the update log at 3.2.1.

I must make rules and processes about translation include process.

Example:
- When coming new translations, make issue for review.
- If no opinions for some periods、I release it. If some opinions coming I tell opinions for pull request author.
- If didn't come no release note translation for some periods, release with no release note.

How about? 

Sorry for my hurried and poor processes.

**Comment by HSSadBoy** [comment]
No problem

**Comment by abc0922001** [comment]
> To avoid contamination, I make issue in [here](https://github.com/Tatsu-syo/noMeiryoUI/issues/81) . How about?

OK
