### ISSUE TITLE
Discussions issue towards next to Version 3.2.1.1

### ISSUE THREAD

**Issue by Tatsu-syo** [Tatsu-syo/noMeiryoUI#81]
In Version 3.2.1, translation confricts occurred.  
To avoid confrict, I put all change information together.

If you make pull request please write information about pull request on this issue.

**Comment by Tatsu-syo** [comment]
I made contribute guide prototype on [pull request Create contribute guide prototype.](https://github.com/Tatsu-syo/noMeiryoUI/pull/82) .

If you have some openions please reply pull request.

**Comment by Tatsu-syo** [comment]
E-mail base contributor Claudio Mantovani Vieira (Portuguese Brazil) will send translations.

I exchange message him and runs process.

**Comment by HSSadBoy** [comment]
When I look at the changelog, I see that 3.2.1 doesn't mention Chinese fixes. I wonder if language fixes won't be written into the changelog, and my personal recommendation is to write them all, even if it's just "update xxx.lang"

**Comment by Tatsu-syo** [comment]
I write "Improve Simplified Chinese(China) and Traditional Chinese(Taiwan) translations.Thanks for HSSadboy and kingofotaku" in Japanese and English changelog.
But, in Simplified Chinese(China) and Traditional Chinese(Taiwan) missing equivalent messages, because I can't write Simplified Chinese(China) and Traditional Chinese(Taiwan). Now translations are depended on authors.
Sorry not to give time to write release note.
On next version I will think message style about language fixes.

**Comment by HSSadBoy** [comment]
Sorry, I didn't consider this factor
 Do you have an official Chinese translation for this software?  I am writing README_CN.md.

**Comment by Tatsu-syo** [comment]
There is Simplified Chinese(China) README.md on [here](https://github.com/Tatsu-syo/noMeiryoUI/pull/83) .
How about?

**Comment by Tatsu-syo** [comment]
And, there is [PR about link to README](https://github.com/Tatsu-syo/noMeiryoUI/pull/84)  on here .
How about?

**Comment by Tatsu-syo** [comment]
I set up contributions rules and prototype documents in English and Japanese and create new PR
[Change branch name into tatsu documents](https://github.com/Tatsu-syo/noMeiryoUI/pull/87) .
If you have any input, please comment on the pull request.
If there are no opinions, I will merge as is.

**Comment by HSSadBoy** [comment]
Seems to be a problem, It should have been look README_CN.md,  I accidentally switched to editing

**Comment by Tatsu-syo** [comment]
@HSSadBoy I merged your fix link for Simplified Chinese(China) version readme. This will not need a review.

And @HSSadBoy sends [pull request to update README_CN.md](https://github.com/Tatsu-syo/noMeiryoUI/pull/89) .

If there are no objections I will merge them.

**Comment by Tatsu-syo** [comment]
@HSSadBoy Few days later, I will merge it.
While few days, anyone can review translations.
I have a drinking party planned for today.

**Comment by Tatsu-syo** [comment]
@HSSadBoy Sorry for not replying to your message sooner.
There are no negative answers.
I merge PR.

**Comment by Tatsu-syo** [comment]
@HSSadBoy sends [pull request to update README_CN.md](https://github.com/Tatsu-syo/noMeiryoUI/pull/94) .

If there are no objections I will merge them on Tuesday.

**Comment by Tatsu-syo** [comment]
@HSSadBoy sends [pull request to update README_CN.md](https://github.com/Tatsu-syo/noMeiryoUI/pull/89) .

If there are no objections I will merge them.

**Comment by Tatsu-syo** [comment]
There are no negative objections.
I merge it.
If you have some improvements, talk in new response or PR.

> I set up contributions rules and prototype documents in English and Japanese and create new PR [Change branch name into tatsu documents](https://github.com/Tatsu-syo/noMeiryoUI/pull/87) . If you have any input, please comment on the pull request. If there are no opinions, I will merge as is.

**Comment by Tatsu-syo** [comment]
This version has spelling error. And, I merged link error fix version.
> @HSSadBoy sends [pull request to update README_CN.md](https://github.com/Tatsu-syo/noMeiryoUI/pull/94) .
> 
> If there are no objections I will merge them on Tuesday.

**Comment by Tatsu-syo** [comment]
New translation fix is coming.
[Fix some typos in README_CN.md](https://github.com/Tatsu-syo/noMeiryoUI/pull/97)
If there are no objections, i will merge this pull request on Wednesday.

**Comment by HSSkyBoy** [comment]
Chinese：我認為這是一次很好的修改，改正了一些連我自己都沒發現的錯誤。但是有一處請希望能按照我圖片中所發送的修改
English：I believe this is a not bad fix, correcting some mistakes I made before that I didn't even notice myself. The only thing that bothers me is what is shown in the picture I sent.
Japanese：私はこれが非常に良い修正だと信じています、以前私が犯した自分自身も気づかなかった誤りを修正しました。唯一に不満の点は私が送った写真に示されているものです。

![鸡你太美.png](https://github.com/Tatsu-syo/noMeiryoUI/assets/122550437/f4f89326-6dd9-40a3-a973-94b7ef951464)

**Comment by Tatsu-syo** [comment]
I update Windows version on main window for Windows 11 2023 Update (23H2)

I create pull request.

If you have some suggestions for this pull request, please comment in [my pull request ](https://github.com/Tatsu-syo/noMeiryoUI/pull/99) .

**Comment by Tatsu-syo** [comment]
I update Windows 11 restriction message for Windows 11 2023 Update (23H2) on Japanese, English, and default language.

I create pull request.

If you have some suggestions for this pull request, please comment in [my pull request](https://github.com/Tatsu-syo/noMeiryoUI/pull/100) .

**Comment by Tatsu-syo** [comment]
There are no objections about credit modification for Windows 11 23H2.

And, I merged below .

- [Windows 11 2023 Update title update](https://github.com/Tatsu-syo/noMeiryoUI/pull/99)
- [Modify restriction message for Windows 2023 Update (23H2).](https://github.com/Tatsu-syo/noMeiryoUI/pull/100)

**Comment by Tatsu-syo** [comment]
I add application font fallback mechanism.

Translators can choice better font in language file FONT_FACE value.

And I make [Pull request](https://github.com/Tatsu-syo/noMeiryoUI/pull/101) .

If you have some suggestions please tell me in pull request review.

**Comment by Tatsu-syo** [comment]
New translations fix for Simplified Chinese(Taiwan) is coming.
https://github.com/Tatsu-syo/noMeiryoUI/pull/102
If there are no objections, i will merge this pull request on January 8.

**Comment by HSSkyBoy** [comment]
> New translations fix for Simplified Chinese(Taiwan)


No problem, I think this pull can be merged.
何も問題ないと思って、このpullは合並できると思います。

**Comment by Tatsu-syo** [comment]
There are no objection about PR [Add application font fallback.](https://github.com/Tatsu-syo/noMeiryoUI/pull/101) and I merge it.

**Comment by Tatsu-syo** [comment]
I make last feature in next version, and create pull request.
[Ability to choce single instance](https://github.com/Tatsu-syo/noMeiryoUI/pull/104)

If there are no objection I will merge 2/12/2004 and calling for translatiors.

**Comment by Tatsu-syo** [comment]
Yesterday, I heard Windows 11 24H2 and build number range.
To prepend  Windows 11 24H2 credit, I create pull request.
[2024 Update credit](https://github.com/Tatsu-syo/noMeiryoUI/pull/105)
It's small change, and If there are no objection I will merge 2/12/2004 and calling for translatiors.

**Comment by Tatsu-syo** [comment]
# It's time to release the new version

## All functions are complete

There are no objections since last week.
And, I merged them into the master branch.
All function in version 3.3.0 are complete.

## Release date plan

I plan to release this version on Feb,25 2024 PM (JST).

## For translators

To release version 3.3.0, I wrote documents and translations in Japanese and English.
I merged these changes into the master branch for translators reference.

For people who want to translate them into their own language, please fork master branch and make pull request.
I will write information about pull request, and translators discuss about contents in pull request.
If no objection in about 4 days or get reach a consensus I merge it in master branch.

If translations arrive after Feb,25 2024 PM (JST), I will include it in next release.

**Comment by Tatsu-syo** [comment]
I am sorry for breaking my own promise.
I push master branch directly to avoid virus scanner problem.
Today, I scan Visual Studio 2022 version execute file, and ESET Security detects noMeiryoUI.exe as suspicious.
To avoid ploblem, I modified source files to compile Visual Studio 2008.
On release, I test virus scanner again.
Sorry for all.

**Comment by Tatsu-syo** [comment]
Today, Feb,25 2024 PM (JST) I release No!! Meiryo UI Version 3.3.0.

About rest problems please discuss on [Discussions issue towards next to 3.3.0](https://github.com/Tatsu-syo/noMeiryoUI/issues/107).

Thank you for all people.
