### ISSUE TITLE
Double start prevention

### ISSUE THREAD

**Issue by superuser7777** [Tatsu-syo/noMeiryoUI#98]
request:
It would be helpful if you could prevent double startup.

-
Thank you, this software saved me a lot.

**Comment by Tatsu-syo** [comment]
Hmm, it's intresting.
But, I think some users (and I) use multiply for compare current settings and changed settings. 
I'll think about it.

**Comment by superuser7777** [comment]
Thank you for considering this.
How about providing it as a command line option like ".ini -set"?

**Comment by Sunshinehero1980** [comment]
字体调大后，行距没变，很挤。能调整行距吗？

**Comment by Tatsu-syo** [comment]
@Sunshinehero1980 Line pitch is depended on font itself.
And, Discussion is suitable this question.

**Comment by Tatsu-syo** [comment]
I implement double start prevention and make pull request #104 .

**Comment by Tatsu-syo** [comment]
I implement  on version 3.3.0 and no response.
This is why, I think this issue can close.
